print("---------BIO-DATA---------")
print("Name           : Almas Banu.Y")
print("Age            : 20")
print("Gender         : Female")
print("Date of Birth  : 15-April-2005")
print("Father's Name  : Yasin Mohammed")
print("Mother's Name  : NagoorAmmal")
print("Address        : Madurai , Tamil Nadu, India")
print("Phone Number   : 9876503211")
print("Email          : almas2005@gmail.com")
print("Education      : B.Sc. Information Technology")
print("Skills         : Python, Node.js, MySQL, MongoDB,Mysql")
print("Languages Known: English, Tamil")
print("---------------------------")