print("====== FAMILY DETAILS ======")
print("Father's Name   : Yasin Mohamed.N")
print("Mother's Name   : NagoorAmmal.K")
print("Younger Sister  : Abees Banu.Y")
print("Family Members  : 4 (Father, Mother, Me, Sister)")
print("--------------------------")
print("======FRIENDS DETAILS======")
print("Friend 1:")
print("Name: Abees")
print("Age: 18")
print("City: Madurai")
print("---------------------------" )
print("Friend 2:")
print("Name: Lavanya")
print("Age: 20")
print("City: Madurai")
print("---------------------------" )
print("Friend 3:")
print("Name: Guru Dharshini")
print("Age: 21")
print("City: Coimbatore")
print("---------------------------" )
print("Friend 4:")
print("Name: Srinithi")
print("Age: 20")
print("City: Trichy")
print("---------------------------" )
print("Friend 5:")
print("Name: Anni Lyfin")
print("Age: 20")
print("City: Salem")
print("---------------------------" )