print("======= MARKS DETAILS =======")
print("----------10th Standard----------")
print("  Tamil   : 67")
print("  English : 63")
print("  Maths   : 56")
print("  Science : 69")
print("  Social  : 71")
print("  Total   : 326")
print("----------12th Standard-----------")
print("  Tamil       : 93")
print("  English     : 75")
print("  Physics     : 84")
print("  Chemistry   : 77")
print("  Computer Sci: 96")
print("  Mathematics : 79")
print("  Total       : 504")
print("------------------------------")
print("  College    :Fatima College")
print("  Major      :Bsc.Information Technology")
print("  Semester 1 : 9.2")
print("  Semester 2 : 9.4")
print("  Semester 3 : 8.5")
print("  Semester 4 : 9.2")
print("  Semester 5 : 7.7")
print("  Semester 6 : 8.3")
print("  Final CGPA : 8.5 / 10")
print("----------------------------")