print("===============sets================")
print("Print the set")
s={"Ravi","Anu","Karthi","Anu","Meena"}
print(s)
print("==============Observe and write why one value is missing============")
print("because doesnot allow duplicates values")
print("===========Add a new student &quot;Suresh&quot; to the students set using add()==========")
s.add("suresh")
print("==========Print the updated set==========")
print(s)
print("===========Create another set named new_students with values===========")
s1={"Divya","Ravi"}
print("=============Update students using update()===========")
s.update(s1)
print("==================Print the result===================")
print(s)
print("=================Remove Meena using remove().===============")
s.remove("Meena")
print(s)
print("Try removing Arun using discard()")
s.discard("Arun")
print(s)
print("=====================Use pop() to remove one element from the set=====================")
s.pop()
print(s)
print("====================Use clear() to remove all elements=====================")
s.clear()
print(s)
print("=====================join set======================")
a = {10, 20, 30, 40}
b = {30, 40, 50, 60}
u=a.union(b)
print(u)
print("====================Intersection====================")
i=a.intersection(b)
print(i)
print("======================Difference (A − B)========================")
d=a.difference(b)
print(d)
print("=========================Symmetric Difference========================")
sd=a.symmetric_difference(b)
print(sd)