print("=========ARITHMETIC OPERATION=========")
a=int(input("Enter a number1:"))
b=int(input("enter a number2:"))
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Modulus",a%b)
print("Square",a**b)
print("Cube",a**3)
print("=========average=======")
c=int(input("enter a number3:"))
tot=a+b+c
avg=tot/3
print("Average:",avg)
print("==========SWAPPING TWO NUMBERS============")
print("Before swapping",a)
print("Before swapping",b)
temp=a
a=b
b=temp
print("After Swapping a:",a)
print("After Swapping b:",b)
print("============check datatypes===========")
print(type(a))
print(type(avg))
d=float(input("enter a number4:"))
add=a+d
print("Add integer and float:",add)
print("datatype of the result:",type(add))
print("=============Relational or Comparison Operator==========")
print("a is  greater number",a>b)
print("b is lesser than a",b<a)
print("a is equal to b:",a==b)
print("a is not equal to b:",a!=b)
print("================Find Total and Average Marks==================")
m1=int(input("enter a m1:"))
m2=int(input("enter a m2:"))
m3=int(input("enter a m3:"))
m4=int(input("enter a m4:"))
m5=int(input("enter a m5:"))
tmark=m1+m2+m3+m4+m5
amarks=tmark/5
print("total marks:",tmark)
print("average marks:",amarks)
print("=============Convert Hours to Minutes===============")
hours = int(input("Enter hours: "))
minutes = hours * 60
print("Minutes:", minutes)
print("Simple Interest")
p=int(input("enter a principle amount:"))
n=int(input("enter a no of years:"))
r=int(input("enter a rate:"))
sim=p*n*r/100
print("simple interest:",sim)
print("===========Find Area of a Rectangle===========")
l=int(input("enter a length:"))
b=int(input("enter a breadth:"))
areaofrectangle=l*b
print("Area of rectangle:",areaofrectangle)
print("==========Check Positive or Negative==========")
print("a is a positive or not",a>0)
print("a is a negative or not",a<0)
print("a is a zero or not",a==0)
print("Calculate Total Cost")
cost=int(input("enter a cost:"))
qty=int(input("enter a number of items:"))
totcost=cost*qty
print("Total cost:",totcost)
print("===========simple calculator==========")
x=float(input("Enter a number1:"))
y=float(input("enter a number2:"))
print("Addition:",x+y)
print("Subtraction:",x-y)
print("Multiplication:",x*y)
print("Division:",x/y)
print("Modulus",x%y)